#workflow repo
name: git_actions demo
run-name: ${{ github.actor }} is learning github actions
on: [push]
env:
  DAY_OF_WEEK: Friday
jobs:
  check_job_status:
    runs-on: ubuntu-latest
    steps:
    - name: current working branch
      run: echo it's currently $DAY_OF_WEEK 
  bash_section:
    runs-on: ubuntu-latest
    steps:
    - name: Run my bash commands
      run: |
        pwd
        echo ${{job.status}} was successful
  run_python:
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: action/checkout@v3
      with:
        repository: Reece-elder/M1-Demo
    - name: run python script in repo
      run: python script.py
    

